/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import Interfaces.IVista;
import controlador.LobbyController;
import red.ClienteRed;
import utileria.GestorAudio;
import javax.swing.*;
import java.awt.*;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.net.URL;

/**
 *
 * @author emiim
 */
public class MenuPrincipal extends javax.swing.JFrame implements IVista{
    private static final String[] AVATARES = {"avatar1", "avatar2", "avatar3", "avatar4", "avatar5", "avatar6"};

    private int avatarSeleccionado = 0;
    private final javax.swing.JLabel etiquetaAvatar = new javax.swing.JLabel();
    private LobbyController controlador;
    /**
     * Creates new form NewJFrame
     */
    
    

    public MenuPrincipal(LobbyController controlador) {
        this.controlador = controlador;
        
        initComponents();
        this.setLocationRelativeTo(null);
        configurarVistaAvatar();
        this.addWindowListener(new java.awt.event.WindowAdapter() {;
                @Override
                public void windowOpened(java.awt.event.WindowEvent evt) {
                    ventanaActual();
                }
        });
        GestorAudio.getInstancia().reproducirMusica("/img/lobby.wav");
        btnRetroseder.addActionListener(this::btnRetrosederActionPerformed);
        txtNombreUsuario.addActionListener(this::btnEntrarActionPerformed);
    }
    public MenuPrincipal() {
        this(null);
    }
    private void ventanaActual() {
        System.out.println("Ventana actual: " + "[" + this.getClass().getSimpleName() + "]");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNombreUsuario = new vista.DiseñosExtras.TextFieldRedondo();
        btnEntrar = new vista.DiseñosExtras.botonCircular();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelDinamicoAvatars = new javax.swing.JPanel();
        btnRetroseder = new javax.swing.JButton();
        btnAvanzar = new javax.swing.JButton();

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pfp.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pfp.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pfp.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/flecha1.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/flecha2.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 109, 109));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/unoLogo.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Avatar");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nombre de Usuario");

        txtNombreUsuario.setRadius(50);
        txtNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreUsuarioActionPerformed(evt);
            }
        });

        btnEntrar.setForeground(new java.awt.Color(0, 0, 0));
        btnEntrar.setText("Entrar");
        btnEntrar.setBorderColor(new java.awt.Color(255, 255, 255));
        btnEntrar.setColor(new java.awt.Color(255, 255, 51));
        btnEntrar.setColorClick(new java.awt.Color(255, 255, 0));
        btnEntrar.setColorOver(new java.awt.Color(255, 255, 51));
        btnEntrar.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnEntrar.setRadius(50);
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        panelDinamicoAvatars.setBackground(new java.awt.Color(255, 255, 255));
        panelDinamicoAvatars.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelDinamicoAvatarsLayout = new javax.swing.GroupLayout(panelDinamicoAvatars);
        panelDinamicoAvatars.setLayout(panelDinamicoAvatarsLayout);
        panelDinamicoAvatarsLayout.setHorizontalGroup(
            panelDinamicoAvatarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 385, Short.MAX_VALUE)
        );
        panelDinamicoAvatarsLayout.setVerticalGroup(
            panelDinamicoAvatarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 111, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panelDinamicoAvatars);

        btnRetroseder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/flecha2.png"))); // NOI18N

        btnAvanzar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/flecha1.png"))); // NOI18N
        btnAvanzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvanzarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(418, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnRetroseder, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(158, 158, 158)))
                        .addGap(18, 18, 18)
                        .addComponent(btnAvanzar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(401, 401, 401))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(464, 464, 464))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(548, 548, 548)
                        .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(618, 618, 618)
                        .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(570, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addGap(551, 551, 551)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(btnAvanzar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(btnRetroseder, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33)))
                .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(318, 318, 318)
                    .addComponent(jLabel8)
                    .addContainerGap(419, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void configurarVistaAvatar() {
        panelDinamicoAvatars.removeAll();
        panelDinamicoAvatars.setLayout(new BorderLayout());
        etiquetaAvatar.setHorizontalAlignment(SwingConstants.CENTER);
        etiquetaAvatar.setVerticalAlignment(SwingConstants.CENTER);
        etiquetaAvatar.setHorizontalTextPosition(SwingConstants.CENTER);
        etiquetaAvatar.setVerticalTextPosition(SwingConstants.BOTTOM);
        etiquetaAvatar.setIcon(cargarAvatar(avatarSeleccionado));
        actualizarAvatarPreview();
        panelDinamicoAvatars.add(etiquetaAvatar, BorderLayout.CENTER);
        panelDinamicoAvatars.revalidate();
        panelDinamicoAvatars.repaint();
    }

    private ImageIcon cargarAvatar(int indice) {
        String ruta = "/img/" + AVATARES[indice] + ".png";
        URL recurso = getClass().getResource(ruta);
        return recurso != null ? new ImageIcon(recurso) : new ImageIcon();
    }

    private void actualizarAvatarPreview() {
        etiquetaAvatar.setIcon(cargarAvatar(avatarSeleccionado));
        etiquetaAvatar.setText("Avatar " + (avatarSeleccionado + 1));
    }

    private String obtenerAvatarSeleccionado() {
        return AVATARES[avatarSeleccionado];
    }

    private void setFormularioHabilitado(boolean habilitado) {
        txtNombreUsuario.setEnabled(habilitado);
        btnEntrar.setEnabled(habilitado);
        btnAvanzar.setEnabled(habilitado);
        btnRetroseder.setEnabled(habilitado);
    }

    private void registrarUsuario() {
        final String nombreJugador = txtNombreUsuario.getText().trim();
        if (nombreJugador.isEmpty()) {
            mostrarMensaje("Ingresa un nombre.");
            return;
        }
        final String avatar = obtenerAvatarSeleccionado();

        if(controlador != null){
            controlador.registrarJugador(nombreJugador,avatar);
        }else{
            mostrarMensaje("error el controlador no esta conectado ala vista");
            setFormularioHabilitado(true);
        }
        
    }

    private void txtNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreUsuarioActionPerformed
        btnEntrarActionPerformed(evt);
    }//GEN-LAST:event_txtNombreUsuarioActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        registrarUsuario();
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void btnAvanzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvanzarActionPerformed
        avatarSeleccionado = (avatarSeleccionado + 1) % AVATARES.length;
        actualizarAvatarPreview();
    }//GEN-LAST:event_btnAvanzarActionPerformed

    private void btnRetrosederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetrosederActionPerformed
        avatarSeleccionado = (avatarSeleccionado - 1 + AVATARES.length) % AVATARES.length;
        actualizarAvatarPreview();
    }//GEN-LAST:event_btnRetrosederActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvanzar;
    private vista.DiseñosExtras.botonCircular btnEntrar;
    private javax.swing.JButton btnRetroseder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel panelDinamicoAvatars;
    private vista.DiseñosExtras.TextFieldRedondo txtNombreUsuario;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actualizar(String evento) {
        revalidate();
        repaint();
    }

    @Override
    public void mostrarVista() {
        setVisible(true);
    }

    @Override
    public void cerrarVista() {
        dispose();
    }

    @Override
    public void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "UNO", JOptionPane.INFORMATION_MESSAGE);
    }
}
